Repository anniversaryArchive/archive-back, pull requests merged in 2022-07, with the labels that each got.

#5 MongoDB 기초 작업
  .gitignore
  app.js
  models/group.js
  routes/group.js
Labels: enhancement

#6 graphql & mongodb 연결
  app.js
  mongodb/mongodb.js
  package.json
  resolvers/index.js
  schema/index.js
Labels: Feature

#7 GraphQL _ Group/Artist 관련 작업
  app.js
  models/artist.js
  models/group.js
  mongodb/mongodb.js
  resolvers/artist.js
  resolvers/group.js
  resolvers/index.js
  routes/group.js
  schema/artist.js
  schema/group.js
  schema/index.js
Labels: Feature

#12 Docs: issue / pull request template
  .github/ISSUE_TEMPLATE/------------------.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#8 Feat: 이미지 관련 기능 구현
  app.js
  models/artist.js
  models/group.js
  models/image.js
  package.json
  resolvers/artist.js
  resolvers/group.js
  resolvers/image.js
  resolvers/index.js
  routes/image.js
  schema/artist.js
  schema/group.js
  schema/image.js
  schema/index.js
  uploads/1656916302852-monstax.png
Labels: Feature

#13 Heroku Hosting
  .gitignore
  Procfile
  app.js
  mongodb/mongodb.js
  package-lock.json
  package.json
Labels: Feature

#15 [Feat] Group 관련 기능 추가 및 변경
  models/artist.js
  models/group.js
  resolvers/artist.js
  resolvers/group.js
  schema/artist.js
  schema/group.js
Labels: Feature

#16 Feat/archive db
  app.js
  models/archive.js
  resolvers/archive.js
  resolvers/index.js
  routes/archive.js
  schema/archive.js
  schema/index.js
Labels: Feature

#20 [Feat] artistPagination filter 추가
  resolvers/artist.js
  schema/artist.js
Labels: Feature
